dist: trusty
# dist: bionic

env:
  global:
    - CC_TEST_REPORTER_ID=141b17e20f44674f1cf65e51f69a32bd3621017fada2a74a3bcf4723b05a0339
    - PGPORT=5433

services:
  - postgresql

addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_script:
  - export RUBYOPT='-W0' # to remove ruby 2.7 warnings
  - cp config/database.yml.travis config/database.yml
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

language: ruby

rvm:
  - 2.7.0

node_js:
  - 12

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

script:
  - yarn install --check-files
  - bundle exec rails db:reset db:setup db:migrate
  - bundle exec rspec
  - bundle exec rubocop --config .rubocop.yml

sudo: required

before_install:
  - sudo apt-get update -qq
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt install -y nodejs
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - gem update --system
  - gem install bundler

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
