# https://github.com/marcelotoledo5000/Dockerfiles/blob/master/alpine3.14-ruby3.4-node20-yarn1.22/Dockerfile
# https://hub.docker.com/repository/docker/skygvinn/alpine3.14-ruby3.4-node20-yarn1.22

version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  server:
    build: .
    container_name: deals
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=vendor/bundle
      - BUNDLE_DISABLE_SHARED_GEMS=1
      - RUBYOPT=-W0
    volumes:
      - .:/var/www/deals:Z
    working_dir: /var/www/deals
    command: bundle exec rails s -b 0.0.0.0
    depends_on:
      - db
