default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: deals_development

test:
  <<: *default
  database: deals_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: deals_production
  username: deals
  password: <%= ENV['DEALS_DATABASE_PASSWORD'] %>
  pool: 10
